// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// unicorn //
// ------- //

#define unicorn_wrap_target 0
#define unicorn_wrap 29

static const uint16_t unicorn_program_instructions[] = {
            //     .wrap_target
    0xe04f, //  0: set    y, 15                      
    0x80e0, //  1: pull   ifempty block              
    0x6061, //  2: out    null, 1                    
    0x7021, //  3: out    x, 1            side 0     
    0xe008, //  4: set    pins, 8                    
    0x0027, //  5: jmp    !x, 7                      
    0xe009, //  6: set    pins, 9                    
    0xb842, //  7: nop                    side 1     
    0x7021, //  8: out    x, 1            side 0     
    0xe008, //  9: set    pins, 8                    
    0x002c, // 10: jmp    !x, 12                     
    0xe009, // 11: set    pins, 9                    
    0xb842, // 12: nop                    side 1     
    0x7021, // 13: out    x, 1            side 0     
    0xe008, // 14: set    pins, 8                    
    0x0031, // 15: jmp    !x, 17                     
    0xe009, // 16: set    pins, 9                    
    0xb842, // 17: nop                    side 1     
    0x0081, // 18: jmp    y--, 1                     
    0x80a0, // 19: pull   block                      
    0x6068, // 20: out    null, 8                    
    0x6061, // 21: out    null, 1                    
    0x6007, // 22: out    pins, 7                    
    0x6030, // 23: out    x, 16                      
    0xe00c, // 24: set    pins, 12                   
    0xe004, // 25: set    pins, 4                    
    0x005a, // 26: jmp    x--, 26                    
    0xe020, // 27: set    x, 0                       
    0xa009, // 28: mov    pins, !x                   
    0xe008, // 29: set    pins, 8                    
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program unicorn_program = {
    .instructions = unicorn_program_instructions,
    .length = 30,
    .origin = -1,
};

static inline pio_sm_config unicorn_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + unicorn_wrap_target, offset + unicorn_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

